### PR TITLE
Convert meshes to OSG's internal format, running the optimizer

### PR DESCRIPTION
**Pull request by doudou**
This is useless right now, but will be picked up automatically if/when https://github.com/Brazilian-Institute-of-Robotics/gui-robot_model/pull/10 gets merged.

### CODE REVIEW

**Comment by gustavoneves12** [comment]
@doudou I tests the results in my machine. The performance was improved, but the meshes quality it not good. Please check the screen shots:

uwcam
oceanviz

It would be good we improve the performance and keep the mesh quality.

**Comment by doudou** [comment]
Actually, the conversion did not change the meshes. I believe that it's that RobotModel was always running the smoothing visitor and I forgot to add it to the Rakefile. Will test that and come back to you (as well as fix the other issues)

**Comment by doudou** [comment]
Updated. Run 'rake clean' and 'rake' to regenerate the osgb files.

I don't want to add .osgb to .gitignore until we decide what to do with the whole thing. If we want them to really be temporary, we should generate them somewhere else. If we want to keep them we'll have to add them to the git somehow.

So, for now, I'd rather keep them 'visible' as a reminder that we have to think about it ;-)

**Comment by doudou** [comment]
removed changed boyancy

**Pull request merged**
