### PR TITLE
uwcam integration

### PR DESCRIPTION
**Pull request by gustavoneves12**
Integrate ocean visualization, thrusters and underwater camera.
Create test scripts to load ocean visualization, thrusters and underwater camera.

### CODE REVIEW

**Comment by doudou** [comment]
unless I am mistaken, 0dc393ee5768b5ba7d706ea423d0b4385f9b3a51 is made obsolete by the --env option of rock-gazebo-viz, no ?

**Comment by gustavoneves12** [comment]
I will test the --env options. I didn't know this option of rock-gazebo-viz. I will test and change the oceanviz-test script to call rock-gazebo-viz, insted of oceanviz-run script.

**Comment by doudou** [comment]
>  didn't know this option of rock-gazebo-viz

Of course not, I wrote it a few days ago and Thomio merged it on Monday or something :P

**Comment by gustavoneves12** [comment]
@doudou to call rock-gazebo-viz I needed to do some changes in the rock-gazebo-viz script.

**Comment by doudou** [comment]
> to call rock-gazebo-viz I needed to do some changes in the rock-gazebo-viz script.

Which changes ?

Could they be made generic and integrated in rock-gazebo-viz ?

**Comment by gustavoneves12** [comment]
I removed the changes in rock-gazebo-viz. I am going to follow your guidelines and set the configuration in the start up script.

**Pull request merged**
